const styles = {
  root: {
    minHeight: "100vh",
    background: "#0a0a0a",
    color: "#e8e2d9",
    fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
    display: "flex",
    flexDirection: "column",
  },

  // Header
  header: {
    borderBottom: "1px solid #1e1e1e",
    background: "#0a0a0a",
    position: "sticky",
    top: 0,
    zIndex: 100,
    backdropFilter: "blur(12px)",
  },
  headerInner: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "16px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logo: { display: "flex", alignItems: "center", gap: 10 },
  logoMark: { color: "#c9a84c", fontSize: 18, lineHeight: 1 },
  logoText: {
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: "0.2em",
    color: "#f0ebe3",
    fontFamily: "'DM Sans', sans-serif",
  },
  logoPill: {
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.12em",
    color: "#c9a84c",
    background: "rgba(201,168,76,0.12)",
    border: "1px solid rgba(201,168,76,0.25)",
    borderRadius: 20,
    padding: "2px 8px",
    textTransform: "uppercase",
  },
  tagline: { fontSize: 12, color: "#444", letterSpacing: "0.04em" },

  // Search section
  searchSection: {
    padding: "48px 24px 40px",
    background: "linear-gradient(180deg, #0f0f0f 0%, #0a0a0a 100%)",
    borderBottom: "1px solid #161616",
  },
  searchSectionInner: {
    maxWidth: 720,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  headline: {
    fontSize: "clamp(28px, 4vw, 44px)",
    fontWeight: 300,
    letterSpacing: "-0.02em",
    color: "#f0ebe3",
    margin: 0,
    lineHeight: 1.2,
    textAlign: "center",
  },
  headlineEm: {
    fontStyle: "italic",
    color: "#c9a84c",
    fontWeight: 400,
  },

  // Search bar
  searchWrap: { width: "100%" },
  searchBox: {
    display: "flex",
    alignItems: "center",
    background: "#111",
    border: "1px solid #2a2a2a",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 0 0 1px transparent, 0 8px 32px rgba(0,0,0,0.4)",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  searchIcon: {
    padding: "0 14px 0 18px",
    color: "#555",
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
  },
  input: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "#f0ebe3",
    fontSize: 16,
    padding: "18px 8px",
    fontFamily: "inherit",
    letterSpacing: "0.01em",
    caretColor: "#c9a84c",
  },
  clearBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#444",
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    transition: "color 0.15s",
  },
  searchBtn: {
    background: "#c9a84c",
    color: "#0a0a0a",
    border: "none",
    cursor: "pointer",
    padding: "18px 28px",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "inherit",
    letterSpacing: "0.06em",
    transition: "background 0.2s, opacity 0.2s",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },

  // Main
  main: { flex: 1, padding: "40px 24px 60px" },
  container: { maxWidth: 1280, margin: "0 auto" },

  // Results meta
  resultsMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 24,
    fontSize: 13,
    color: "#666",
    flexWrap: "wrap",
  },
  metaQuery: { color: "#c9a84c", fontWeight: 600 },
  metaDivider: { color: "#333" },
  metaCount: { color: "#888" },
  metaRange: { color: "#555" },

  // Grid
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 20,
    marginBottom: 32,
  },

  // Card
  card: {
    background: "#111",
    border: "1px solid #1c1c1c",
    borderRadius: 12,
    overflow: "hidden",
    cursor: "pointer",
    transition:
      "transform 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease",
    animation: "fadeSlideUp 0.4s ease both",
  },
  cardHover: {
    transform: "translateY(-4px)",
    borderColor: "#2e2e2e",
    boxShadow: "0 16px 48px rgba(0,0,0,0.5), 0 0 0 1px #c9a84c22",
  },
  imageWrap: {
    position: "relative",
    aspectRatio: "4/3",
    background: "#181818",
    overflow: "hidden",
  },
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.4s ease",
    display: "block",
  },
  imgPlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#151515",
  },
  discountBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    background: "#c9a84c",
    color: "#0a0a0a",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.04em",
    padding: "3px 8px",
    borderRadius: 20,
  },
  cardBody: { padding: "14px 16px 16px" },
  productName: {
    margin: "0 0 10px",
    fontSize: 13,
    color: "#c8c2b8",
    lineHeight: 1.45,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    fontWeight: 400,
    letterSpacing: "0.01em",
  },
  priceRow: { display: "flex", alignItems: "center", gap: 8 },
  price: { fontSize: 15, fontWeight: 700, color: "#f0ebe3" },
  msrp: {
    fontSize: 12,
    color: "#555",
    textDecoration: "line-through",
    fontWeight: 400,
  },

  // Pagination
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    margin: "28px 0",
    flexWrap: "wrap",
  },
  pageBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#111",
    border: "1px solid #2a2a2a",
    color: "#e8e2d9",
    padding: "10px 18px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "inherit",
    letterSpacing: "0.04em",
    transition: "background 0.15s, border-color 0.15s",
  },
  pageBtnDisabled: {
    opacity: 0.3,
    cursor: "not-allowed",
    pointerEvents: "none",
  },
  pageNumbers: { display: "flex", alignItems: "center", gap: 4 },
  pageNumber: {
    minWidth: 38,
    height: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    border: "1px solid #222",
    color: "#888",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "inherit",
    fontWeight: 500,
    transition: "background 0.15s, color 0.15s, border-color 0.15s",
  },
  pageNumberActive: {
    background: "#c9a84c",
    borderColor: "#c9a84c",
    color: "#0a0a0a",
    fontWeight: 700,
  },
  ellipsis: { color: "#444", padding: "0 4px", fontSize: 14 },

  // Skeleton
  skeletonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 20,
  },
  skeleton: {
    background: "#111",
    border: "1px solid #1c1c1c",
    borderRadius: 12,
    overflow: "hidden",
  },
  skeletonImg: {
    aspectRatio: "4/3",
    width: "100%",
    background: "#1a1a1a",
  },
  skeletonLine: {
    height: 12,
    background: "#1a1a1a",
    borderRadius: 4,
    margin: "8px 0",
  },

  // Empty / Error
  empty: {
    textAlign: "center",
    padding: "80px 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  emptyIcon: { marginBottom: 8, opacity: 0.5 },
  emptyTitle: { fontSize: 18, fontWeight: 600, color: "#c8c2b8", margin: 0 },
  emptyText: { fontSize: 14, color: "#555", margin: 0 },
  retryBtn: {
    marginTop: 16,
    background: "#c9a84c",
    color: "#0a0a0a",
    border: "none",
    padding: "10px 24px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 700,
    fontFamily: "inherit",
    fontSize: 13,
  },

  // Hero idle
  hero: {
    textAlign: "center",
    padding: "80px 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
  },
  heroGlyph: {
    fontSize: 40,
    color: "#c9a84c",
    opacity: 0.35,
    lineHeight: 1,
    animation: "pulse 3s ease-in-out infinite",
  },
  heroHeadline: {
    fontSize: 24,
    fontWeight: 300,
    color: "#5a5a5a",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  heroSub: {
    fontSize: 14,
    color: "#383838",
    margin: 0,
    maxWidth: 360,
  },
  chips: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 8,
  },
  chip: {
    fontSize: 12,
    color: "#444",
    border: "1px solid #222",
    borderRadius: 20,
    padding: "5px 14px",
    letterSpacing: "0.04em",
  },

  // Footer
  footer: {
    borderTop: "1px solid #161616",
    padding: "20px 24px",
    textAlign: "center",
    fontSize: 12,
    color: "#333",
    letterSpacing: "0.04em",
  },
};

export default styles;